/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONST = 1;
  /** RegularExpression Id. */
  int TRUE = 2;
  /** RegularExpression Id. */
  int FALSE = 3;
  /** RegularExpression Id. */
  int CONSTR = 4;
  /** RegularExpression Id. */
  int THIS = 5;
  /** RegularExpression Id. */
  int FUNC = 6;
  /** RegularExpression Id. */
  int RETURN = 7;
  /** RegularExpression Id. */
  int READ = 8;
  /** RegularExpression Id. */
  int WRITE = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int THEN = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int ID = 16;
  /** RegularExpression Id. */
  int VARID = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int ADD = 19;
  /** RegularExpression Id. */
  int ADDASSIGN = 20;
  /** RegularExpression Id. */
  int SUBASSIGN = 21;
  /** RegularExpression Id. */
  int MULASSIGN = 22;
  /** RegularExpression Id. */
  int SUB = 23;
  /** RegularExpression Id. */
  int MUL = 24;
  /** RegularExpression Id. */
  int POW = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int MOD = 27;
  /** RegularExpression Id. */
  int LCB = 28;
  /** RegularExpression Id. */
  int RCB = 29;
  /** RegularExpression Id. */
  int LBR = 30;
  /** RegularExpression Id. */
  int RBR = 31;
  /** RegularExpression Id. */
  int EQ = 32;
  /** RegularExpression Id. */
  int NOT = 33;
  /** RegularExpression Id. */
  int NEQ = 34;
  /** RegularExpression Id. */
  int GT = 35;
  /** RegularExpression Id. */
  int LT = 36;
  /** RegularExpression Id. */
  int GOE = 37;
  /** RegularExpression Id. */
  int LOE = 38;
  /** RegularExpression Id. */
  int ARROW = 39;
  /** RegularExpression Id. */
  int COMPARISON = 40;
  /** RegularExpression Id. */
  int AND = 41;
  /** RegularExpression Id. */
  int OR = 42;
  /** RegularExpression Id. */
  int SC = 43;
  /** RegularExpression Id. */
  int STRLIT = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"const\"",
    "\"true\"",
    "\"false\"",
    "\"construct\"",
    "\"this\"",
    "\"function\"",
    "\"return\"",
    "\"read\"",
    "\"write\"",
    "\"class\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"asLongAs\"",
    "<INT>",
    "<ID>",
    "<VARID>",
    "<COMMA>",
    "<ADD>",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "<SUB>",
    "<MUL>",
    "\"**\"",
    "<DIV>",
    "<MOD>",
    "<LCB>",
    "<RCB>",
    "<LBR>",
    "<RBR>",
    "<EQ>",
    "<NOT>",
    "\"!=\"",
    "<GT>",
    "<LT>",
    "\">=\"",
    "\"<=\"",
    "\"->\"",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "<SC>",
    "<STRLIT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 49>",
    "<token of kind 50>",
  };

}
